language: java
before_install:
  - bash .travis/setup-secrets.sh
  - bash .travis/configure-maven.sh
  - . .travis/install-openjdk.sh "11.0.8+10"
install: ./mvnw install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
before_script: true
script:
  - 'bash .travis/deploy.sh'
after_success: true

notifications:
  email:
    recipients:
    - andreas.dangel@adangel.org
    on_success: always
    on_failure: always
cache:
  directories:
  - "$HOME/.m2"
  - "$HOME/.cache"

#
# Required Secure Variables:
#
# CI_DEPLOY_USERNAME - the user which can upload net.sourceforge.pmd:* to https://oss.sonatype.org/
# CI_DEPLOY_PASSWORD
#
# CI_SIGN_KEYNAME - GPG key used to sign the release jar before uploading to maven central
# CI_SIGN_PASSPHRASE

env:
  global:
  - secure: "irfh3kJZsEKsUgL0EwPFEOK0pl8aO0wHm5PRr/HSURhL179xQA5gmVFZFg9gtaH4xNgqGuqvVmnhB9MmhAa1vmns/wnTQyZzYl+JfzaAZTAMxazOXKh/qtOZtZZGauueuSpTJpJeBTbNgYcqpvSUkOAbAl68GJbmnJUco7IauD3SmpcG8tDL5nzW0hIcuXg/R5FrG5lw/G3LkOtVxBEhgUFD6nYPlIm4v2HHycI8nTv2csWTiyGITpML7CMawywVlQ3mZ4BTwSOy1bdJBXk8Y3fDsrxs3aLizMkgYWvcfQl505gXsTbzQ7OOOs2E83XR7Ubsw+yPaCH1u65nwEMBrLFPOXpGgFCTckbNyW0H1bcIH0Ym8cV4ji6gymyu+tncm42WZK4hdyvpNOutjnwC6j4fwTWvEfVa8mK6HEGFTXSniO1RxdOhgxqNjPdYnBLsxm/i5CHMtH3DBesq/i7Zfr6qK9h0Mzk2j+xXw8o71ecr3F7D7tUKnycQCglWYs9lS35Cwtj61BcLHXZ0alDoY6t8/WQCEFZSan1aLYXnHii7utuapQzV/sJiV422vWviXO1+qJrowVYARkYKven3A+uCd5Ki1/TecZfiXpWhCBIAJxSOgJGVE6vuhjp2MQnP8HTLXGH6cNGIKaHkqQIy9lC1L97NBXjd5MxiVuT4YT8="
  - secure: "0exDuU/vTeQ4GdiY1RmfsN9+eMcMgEU93Wmh5rO6BvYvZfD/nI8a1/S8WsBG0poMksf6ZQe/P1mILByRlCRagmBqVKqprE1ennYP1GY+T6i5JMjE9R7iAaY35eISbU45f/UhQjfRgBuWYYYlFpAbj8pyBf0AyFjgQh+2CJI/tm8Bx2aUPoaA8TM6llK7SOR/Hzo04DWLMV/PDJOPqntcp9oKWl5KuV3SklJmYFJ9TSSTtE350ibM8emnoPMaXKSuSbrbfT70PbOXcQ92AukEb3XRbKwlPxx70Z0UagWfat4z1+MZvGUgR3MyumfbmZFLzxaFYVJy6v4n0n5WYV4aWiNbVnJtqHBjNPGAM8QKgj/RStQG+OI15SktrfS4gS0+pQaoLMOTI7t9w9dOj9q29BK1832Bcxr11oydCKnS6wyliSCnlYPJWTIRhzZ20ZSmLkXzGukMv+zw2l9/hcPEFiASdVJ84QaaW7Sy8Krfat8YDP2y9ZOtMj7STzv/oltlIgJKfQN/+35DHYB3dxERF0fxgtNNFUtWcYuGjwLbk3Bxar/mdWK7LWi/4GA+T+6gHHdY8/yp6LTXPDMf6nVEOircEm9BdRhUTiW85+OjmapVyEcDOFyJdE8arRE9J/2k8glPHHGyZqkHNO0MBpt+563I8syDTX1rx7uahC4pUIQ="
  - secure: "ARJuJ1QA/VpcgkrmlvrCr0Z0dONMbTdPMqg0ABk+YBjoc4WExwZYuKVBn/6682SWUV3MR8WfLjO/qOcQnwl8ERL3K2ywFnHExKxdWCZbMfWEMonGsuyaV25FN7zYRziZDzq6Lg1Tb0crWGHk57gHoWt48dPLh1/2Q+DNWR2LmU+ZVf2fGzJZ+dwSm6EwiNKW4brDGDryQuvLr9/aFCGh23L0kLaAcNFEGqBsZPjVUIZFMXu2/ENf98wao2KJhoJkp+b6IAtdzpyJeaXwf6a2Qrtb+wNzi5mcS2XAJc9P5OrLRnJmTMeuxi2qXC+rxa8e9b9ux9LBK2c4wNtIFvtDCDhPDiLIlbqv9ZByNnWofViXqPwVz/8Lo+iWfBGsoXf5FarL3E0gopHsQQIwKzL7Gd4YkBA1DzHWoyqKF2IG8yODaaNU1M4k5EqOSCgKUVlbLX/rgasSYxubOldhFuJvt29SLrgwRxAgFO2gXApFgwhmI+Sc3fzHy47jOyRnvPxF4jxM5s6sG9osSfpzEgWh16RxRFyMqYxghyIYpKkXRIjhx2qT/Jl3wmQf20/oHERUvJYO0FpthXQoikqdHqNG6j2p9ueHQgwB4Sqg1lQGQhfR37N8q5YlBN3i3VL98vEGy9GrMAX/CegLawUR2piPtjjY2zfL0MI9rITzSvu2ip0="
  - secure: "a1rRJGXEwXevxoIXdLQ6sNRDgcT4zMDdo3rEQyZ/XhiJvRUhOwSvyn0FXscPlC52PgRlBharRNZQpW7cEYGRsrkn1/wbCrhid5vWsNm7Puj0ONTap31CbT8QF6mr9Xsw301USU/ZtumtIivbvKvsDdASsOIwKe226JOQnjSty5Hjv+78XBW3nMLTVv0UVuqaA6fPMeqPTrXUI2/OcA+mwF5RA8WZ6LPlBxztIQcgDWVzOuibYcrVK2vsiK+JdQP1xvHsfMEO6xGSUqS6efpg05kbZnSwfttbpH8zATzDpaUsI1+R51FsMmZyBiqe3hruCa74eHxBCYLXbTmsZPFzQMohKWXDEaOjrpbXH+suLUkNWuzEZFImRe8qHnzUtfmEiOxk3Tx2V5TnDvfFjB4ulLG5ItEWVHH4fBDkjrf6tMp4CLRHpowWSdizoUpPso8fDkjHluFCStKP3fhCLRuoH61BhqRvxHgolgucAtZPVVGulx7qbLvmsda60ZMfBWJDfHL9GZE9S6h9XFEsUeCJy4UKOopXGwA+2LeCWSwgcp4BaoR9RG5PQHaN1zicMaCsZrBUnPgQwOfuxYz0DeR4pqvYoSslzV39z/mkc1JOUh/6YjkfcfAQfrGZHNbLXh3rUnZWi8VAu+Eued7+tGbXvukGOlnJ9khMr44JawVdmLQ="

