name: build

on:
  push:
    branches:
      - main
      - master
    tags:
      - '**'
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    continue-on-error: false
    if: ${{ !contains(github.event.head_commit.message, '[skip ci]') }}
    steps:
    - uses: actions/checkout@v2
    - uses: actions/cache@v2
      with:
        path: |
          ~/.m2/repository
          ~/.cache
        key: ${{ runner.os }}-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-
    - name: Set Locale
      shell: bash
      run: |
        echo "LANG=en_US.UTF-8" >> $GITHUB_ENV
    - name: Check Environment
      shell: bash
      run: |
        f=check-environment.sh; \
        mkdir -p .ci && \
        ( [ -e .ci/$f ] || curl -sSL "${PMD_CI_SCRIPTS_URL}/$f" > ".ci/$f" ) && \
        chmod 755 .ci/$f && \
        .ci/$f
      env:
        PMD_CI_SCRIPTS_URL: https://raw.githubusercontent.com/adangel/build-tools/gh-action-scripts/scripts
    - name: Build
      run: .ci/build.sh
      shell: bash
      env:
        MAVEN_OPTS: -Dmaven.wagon.httpconnectionManager.ttlSeconds=180 -Dmaven.wagon.http.retryHandler.count=3
        PMD_CI_SCRIPTS_URL: https://raw.githubusercontent.com/adangel/build-tools/gh-action-scripts/scripts
        PMD_CI_SECRET_PASSPHRASE: ${{ secrets.PMD_CI_SECRET_PASSPHRASE }}
